-- Gerado por generate-linhas-gtfs.py a partir de routes.txt
-- Linhas unicas (route_short_name): 516
USE unibus;

SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM ocorrencia;
DELETE FROM linha;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO linha (numero_linha, nome_linha, origem, destino) VALUES
('636', 'Merck - Saens Peña', 'Merck', 'Saens Peña'),
('805', 'Terminal Alvorada - Jardim Oceânico', 'Terminal Alvorada', 'Jardim Oceânico'),
('497', 'Penha - Largo do Machado', 'Penha', 'Largo do Machado'),
('2343', 'Ribeira - Castelo', 'Ribeira', 'Castelo'),
('2305', 'Jardim América - Castelo', 'Jardim América', 'Castelo'),
('2342', 'Bananal - Castelo', 'Bananal', 'Castelo'),
('2344', 'Bancários - Castelo', 'Bancários', 'Castelo'),
('254', 'Madureira - Candelária', 'Madureira', 'Candelária'),
('238', 'Água Santa - Castelo', 'Água Santa', 'Castelo'),
('SN238', 'Água Santa - Castelo', 'Água Santa', 'Castelo'),
('247', 'Camarista Méier - Passeio', 'Camarista Méier', 'Passeio'),
('249', 'Água Santa - Carioca', 'Água Santa', 'Carioca'),
('265', 'Marechal Hermes - Castelo', 'Marechal Hermes', 'Castelo'),
('SN265', 'Marechal Hermes - Castelo', 'Marechal Hermes', 'Castelo'),
('277', 'Rocha Miranda - Candelária', 'Rocha Miranda', 'Candelária'),
('519', 'Urca - Copacabana', 'Urca', 'Copacabana'),
('518', 'Urca - Botafogo', 'Urca', 'Botafogo'),
('915', 'Bonsucesso - Aeroporto Internacional do RJ', 'Bonsucesso', 'Aeroporto Internacional do RJ'),
('232', 'Lins de Vasconcelos - Castelo', 'Lins de Vasconcelos', 'Castelo'),
('885', 'Terminal Mato Alto - Santa Cruz', 'Terminal Mato Alto', 'Santa Cruz'),
('SPB550', 'Tijuquinha - Gávea', 'Tijuquinha', 'Gávea'),
('SV831', 'Colônia - Terminal Taquara', 'Colônia', 'Terminal Taquara'),
('SV692', 'Méier - Terminal Alvorada', 'Méier', 'Terminal Alvorada'),
('SN232', 'Lins de Vasconcelos - Castelo', 'Lins de Vasconcelos', 'Castelo'),
('292', 'Engenho da Rainha - Castelo', 'Engenho da Rainha', 'Castelo'),
('765', 'Mendanha - Terminal Deodoro', 'Mendanha', 'Terminal Deodoro'),
('296', 'Irajá - Castelo', 'Irajá', 'Castelo'),
('SV866', 'Terminal Campo Grande - Terminal Pingo d''Água', 'Terminal Campo Grande', 'Terminal Pingo d''Água'),
('753', 'Santa Cruz - Metrô Coelho Neto', 'Santa Cruz', 'Metrô Coelho Neto'),
('298', 'Acari - Castelo', 'Acari', 'Castelo'),
('311', 'Engenheiro Leal - Candelária', 'Engenheiro Leal', 'Candelária'),
('SP803', 'Jabour - Terminal Sulacap', 'Jabour', 'Terminal Sulacap'),
('312', 'Olaria - Candelária', 'Olaria', 'Candelária'),
('313', 'Penha (Grotão) - Praça Tiradentes', 'Penha (Grotão)', 'Praça Tiradentes'),
('321', 'Bancários - Castelo', 'Bancários', 'Castelo'),
('323', 'Bananal - Castelo', 'Bananal', 'Castelo'),
('325', 'Ribeira - Castelo', 'Ribeira', 'Castelo'),
('326', 'Bancários - Candelária', 'Bancários', 'Candelária'),
('327', 'Ribeira - Castelo', 'Ribeira', 'Castelo'),
('328', 'Bananal - Candelária', 'Bananal', 'Candelária'),
('329', 'Bancários - Candelária', 'Bancários', 'Candelária'),
('342', 'Jardim América - Castelo', 'Jardim América', 'Castelo'),
('SR342', 'Jardim América - Castelo', 'Jardim América', 'Castelo'),
('349', 'Rocha Miranda - Castelo', 'Rocha Miranda', 'Castelo'),
('355', 'Madureira - Praça Tiradentes', 'Madureira', 'Praça Tiradentes'),
('SR355', 'Madureira - Praça Tiradentes', 'Madureira', 'Praça Tiradentes'),
('362', 'Honório Gurgel - Castelo', 'Honório Gurgel', 'Castelo'),
('SR362', 'Honório Gurgel - Castelo', 'Honório Gurgel', 'Castelo'),
('378', 'Marechal Hermes - Castelo', 'Marechal Hermes', 'Castelo'),
('SR378', 'Marechal Hermes - Castelo', 'Marechal Hermes', 'Castelo'),
('384', 'Pavuna - Passeio', 'Pavuna', 'Passeio'),
('385', 'Village Pavuna - Passeio', 'Village Pavuna', 'Passeio'),
('SN324', 'Ribeira - Candelária', 'Ribeira', 'Candelária'),
('SN298', 'Acari - Castelo', 'Acari', 'Castelo'),
('399', 'Pavuna - Passeio', 'Pavuna', 'Passeio'),
('SP404', 'Caju - Leblon', 'Caju', 'Leblon'),
('455', 'Méier - Copacabana', 'Méier', 'Copacabana'),
('457', 'Abolição - Copacabana', 'Abolição', 'Copacabana'),
('483', 'Penha - General Osório', 'Penha', 'General Osório'),
('484', 'Olaria - General Osório', 'Olaria', 'General Osório'),
('492', 'Bancários - Prado Júnior', 'Bancários', 'Prado Júnior'),
('386', 'Anchieta - Candelária', 'Anchieta', 'Candelária'),
('621', 'Penha - Saens Peña', 'Penha', 'Saens Peña'),
('622', 'Penha - Saens Peña', 'Penha', 'Saens Peña'),
('623', 'Penha - Saens Peña', 'Penha', 'Saens Peña'),
('624', 'Mariópolis - Praça da Bandeira', 'Mariópolis', 'Praça da Bandeira'),
('625', 'Olaria - Saens Peña', 'Olaria', 'Saens Peña'),
('627', 'Inhaúma - Saens Peña', 'Inhaúma', 'Saens Peña'),
('628', 'Penha - Nova América', 'Penha', 'Nova América'),
('629', 'Irajá - Saens Peña', 'Irajá', 'Saens Peña'),
('630', 'Penha (IAPI) - Saens Peña', 'Penha (IAPI)', 'Saens Peña'),
('634', 'Bananal - Saens Peña', 'Bananal', 'Saens Peña'),
('638', 'Marechal Hermes - Saens Peña', 'Marechal Hermes', 'Saens Peña'),
('639', 'Jardim América - Saens Peña', 'Jardim América', 'Saens Peña'),
('650', 'Marechal Hermes - Engenho Novo', 'Marechal Hermes', 'Engenho Novo'),
('665', 'Pavuna - Saens Peña', 'Pavuna', 'Saens Peña'),
('SVB665', 'Pavuna - Saens Peña', 'Pavuna', 'Saens Peña'),
('669', 'Pavuna - Méier', 'Pavuna', 'Méier'),
('SV669', 'Pavuna - Méier', 'Pavuna', 'Méier'),
('679', 'Grotão - Méier', 'Grotão', 'Méier'),
('687', 'Pavuna - Méier', 'Pavuna', 'Méier'),
('688', 'Méier - Pavuna', 'Méier', 'Pavuna'),
('696', 'Méier - Praia do Dendê', 'Méier', 'Praia do Dendê'),
('711', 'Rocha Miranda - Rio Comprido', 'Rocha Miranda', 'Rio Comprido'),
('721', 'Vila Cruzeiro - Cascadura', 'Vila Cruzeiro', 'Cascadura'),
('778', 'Pavuna - Cascadura', 'Pavuna', 'Cascadura'),
('SN629', 'Irajá - Saens Peña', 'Irajá', 'Saens Peña'),
('SN457', 'Abolição - Copacabana', 'Abolição', 'Copacabana'),
('SN639', 'Jardim América - Saens Peña', 'Jardim América', 'Saens Peña'),
('901', 'Bonsucesso - Bananal', 'Bonsucesso', 'Bananal'),
('905', 'Bonsucesso - Irajá', 'Bonsucesso', 'Irajá'),
('906', 'Jardim América - Caju', 'Jardim América', 'Caju'),
('SV606', 'Engenho de Dentro - Terminal Gentileza', 'Engenho de Dentro', 'Terminal Gentileza'),
('910', 'Bananal - Irajá', 'Bananal', 'Irajá'),
('913', 'Del Castilho - Fundão', 'Del Castilho', 'Fundão'),
('920', 'Pavuna - Bonsucesso', 'Pavuna', 'Bonsucesso'),
('928', 'Marechal Hermes - Bonsucesso', 'Marechal Hermes', 'Bonsucesso'),
('663', 'Méier - Fundão', 'Méier', 'Fundão'),
('LECD140', 'Terminal Margaridas - Méier', 'Terminal Margaridas', 'Méier'),
('LECD141', 'Terminal Margaridas - Méier', 'Terminal Margaridas', 'Méier'),
('LECD144', 'Metrô Vicente de Carvalho - Terminal Margaridas', 'Metrô Vicente de Carvalho', 'Terminal Margaridas'),
('LECD145', 'Metrô Vicente de Carvalho - Terminal Margaridas', 'Metrô Vicente de Carvalho', 'Terminal Margaridas'),
('LECD147', 'Metrô Pavuna - Saens Peña', 'Metrô Pavuna', 'Saens Peña'),
('315', 'Central - Recreio dos Bandeirantes', 'Central', 'Recreio dos Bandeirantes'),
('306', 'Praça Seca - Castelo', 'Praça Seca', 'Castelo'),
('338', 'Taquara - Candelária', 'Taquara', 'Candelária'),
('341', 'Taquara - Candelária', 'Taquara', 'Candelária'),
('343', 'Jardim Oceânico - Candelária', 'Jardim Oceânico', 'Candelária'),
('SP343', 'Rio das Pedras - Candelária', 'Rio das Pedras', 'Candelária'),
('348', 'Riocentro - Candelária', 'Riocentro', 'Candelária'),
('363', 'Vila Valqueire - Candelária', 'Vila Valqueire', 'Candelária'),
('SV363', 'Vila Valqueire - Candelária', 'Vila Valqueire', 'Candelária'),
('368', 'Riocentro - Candelária', 'Riocentro', 'Candelária'),
('380', 'Curicica - Candelária', 'Curicica', 'Candelária'),
('793', 'Pavuna - Terminal Sulacap', 'Pavuna', 'Terminal Sulacap'),
('SN363', 'Vila Valqueire - Candelária', 'Vila Valqueire', 'Candelária'),
('SN302', 'Terminal Gentileza - Terminal Alvorada', 'Terminal Gentileza', 'Terminal Alvorada'),
('390', 'Curicica - Candelária', 'Curicica', 'Candelária'),
('550', 'Cidade de Deus - Gávea', 'Cidade de Deus', 'Gávea'),
('555', 'Rio das Pedras - Gávea', 'Rio das Pedras', 'Gávea'),
('557', 'Rio das Pedras - Copacabana', 'Rio das Pedras', 'Copacabana'),
('565', 'Tanque - Gávea', 'Tanque', 'Gávea'),
('600', 'Taquara - Saens Peña', 'Taquara', 'Saens Peña'),
('361', 'Recreio dos Bandeirantes - Castelo', 'Recreio dos Bandeirantes', 'Castelo'),
('2111', 'Praça Seca - Castelo', 'Praça Seca', 'Castelo'),
('2110', 'Gardênia Azul - Castelo', 'Gardênia Azul', 'Castelo'),
('2112', 'Taquara - Castelo', 'Taquara', 'Castelo'),
('2114', 'Freguesia - Castelo', 'Freguesia', 'Castelo'),
('2345', 'Vila Valqueire - Castelo', 'Vila Valqueire', 'Castelo'),
('601', 'Santa Maria - Saens Peña', 'Santa Maria', 'Saens Peña'),
('352', 'Riocentro - Candelária', 'Riocentro', 'Candelária'),
('607', 'Cascadura - Rio Comprido', 'Cascadura', 'Rio Comprido'),
('610', 'Del Castilho - Tanque', 'Del Castilho', 'Tanque'),
('611', 'Camorim - Del Castilho', 'Camorim', 'Del Castilho'),
('613', 'Vargem Grande - Del Castilho', 'Vargem Grande', 'Del Castilho'),
('SPA613', 'Riocentro - Del Castilho', 'Riocentro', 'Del Castilho'),
('678', 'Méier - Vila Valqueire', 'Méier', 'Vila Valqueire'),
('712', 'Cascadura - Irajá', 'Cascadura', 'Irajá'),
('766', 'Madureira - Freguesia', 'Madureira', 'Freguesia'),
('774', 'Madureira - Jardim América', 'Madureira', 'Jardim América'),
('775', 'Jardim América - Madureira', 'Jardim América', 'Madureira'),
('829', 'Gardênia Azul - Freguesia', 'Gardênia Azul', 'Freguesia'),
('810', 'Terminal Taquara - Pontal', 'Terminal Taquara', 'Pontal'),
('831', 'Colônia - Terminal Taquara', 'Colônia', 'Terminal Taquara'),
('302', 'Terminal Gentileza - Terminal Alvorada', 'Terminal Gentileza', 'Terminal Alvorada'),
('SN565', 'Tanque - Gávea', 'Tanque', 'Gávea'),
('844', 'Jardim Oceânico - Barrinha', 'Jardim Oceânico', 'Barrinha'),
('SN550', 'Cidade de Deus - Gávea', 'Cidade de Deus', 'Gávea'),
('SP810', 'Terminal Taquara - Vargem Grande', 'Terminal Taquara', 'Vargem Grande'),
('859', 'Covanca - Largo do Tanque', 'Covanca', 'Largo do Tanque');

INSERT INTO linha (numero_linha, nome_linha, origem, destino) VALUES
('861', 'Rio das Pedras - Curicica', 'Rio das Pedras', 'Curicica'),
('878', 'Tanque - Barra da Tijuca', 'Tanque', 'Barra da Tijuca'),
('SV878', 'Tanque - Barra da Tijuca', 'Tanque', 'Barra da Tijuca'),
('SN636', 'Merck - Saens Peña', 'Merck', 'Saens Peña'),
('863', 'Rio das Pedras - Barra da Tijuca', 'Rio das Pedras', 'Barra da Tijuca'),
('862', 'Rio das Pedras - Barra da Tijuca', 'Rio das Pedras', 'Barra da Tijuca'),
('693', 'Méier - Terminal Alvorada', 'Méier', 'Terminal Alvorada'),
('692', 'Méier - Terminal Alvorada', 'Méier', 'Terminal Alvorada'),
('614', 'Del Castilho - Terminal Alvorada', 'Del Castilho', 'Terminal Alvorada'),
('SN810', 'Terminal Taquara - Pontal', 'Terminal Taquara', 'Pontal'),
('880', 'Rio das Pedras - Terminal Alvorada', 'Rio das Pedras', 'Terminal Alvorada'),
('932', 'Gardênia Azul - Tanque', 'Gardênia Azul', 'Tanque'),
('940', 'Ramos (Praia) - Madureira', 'Ramos (Praia)', 'Madureira'),
('652', 'Cascadura - Méier', 'Cascadura', 'Méier'),
('369', 'Bangu - Candelária', 'Bangu', 'Candelária'),
('383', 'Realengo - Praça da República', 'Realengo', 'Praça da República'),
('388', 'Santa Cruz - Candelária', 'Santa Cruz', 'Candelária'),
('393', 'Bangu - Candelária', 'Bangu', 'Candelária'),
('SR393', 'Bangu - Candelária', 'Bangu', 'Candelária'),
('2307', 'Jardim 7 de Abril - Carioca', 'Jardim 7 de Abril', 'Carioca'),
('2308', 'Cosmos - Carioca', 'Cosmos', 'Carioca'),
('2309', 'Urucânia - Carioca', 'Urucânia', 'Carioca'),
('2310', 'Bangu - Candelária', 'Bangu', 'Candelária'),
('2803', 'Vila Kennedy - Terminal Alvorada', 'Vila Kennedy', 'Terminal Alvorada'),
('900', 'Taquara - Downtown', 'Taquara', 'Downtown'),
('865', 'Pau da Fome - Terminal Taquara', 'Pau da Fome', 'Terminal Taquara'),
('954', 'Terminal Taquara - Recreio dos Bandeirantes', 'Terminal Taquara', 'Recreio dos Bandeirantes'),
('SN954', 'Terminal Taquara - Recreio dos Bandeirantes', 'Terminal Taquara', 'Recreio dos Bandeirantes'),
('SN393', 'Bangu - Candelária', 'Bangu', 'Candelária'),
('SR300', 'Terminal Sulacap - Candelária', 'Terminal Sulacap', 'Candelária'),
('SN878', 'Tanque - Barra da Tijuca', 'Tanque', 'Barra da Tijuca'),
('2336', 'Campo Grande - Castelo', 'Campo Grande', 'Castelo'),
('2303', 'Cesarão - Carioca', 'Cesarão', 'Carioca'),
('2334', 'Campo Grande - Castelo', 'Campo Grande', 'Castelo'),
('2335', 'Santa Cruz - Castelo', 'Santa Cruz', 'Castelo'),
('2337', 'Santa Cruz - Castelo', 'Santa Cruz', 'Castelo'),
('2339', 'Campo Grande - Castelo', 'Campo Grande', 'Castelo'),
('2381', 'Pedra de Guaratiba - Castelo', 'Pedra de Guaratiba', 'Castelo'),
('2383', 'Sepetiba - Carioca', 'Sepetiba', 'Carioca'),
('2802', 'Santa Cruz - Barra da Tijuca', 'Santa Cruz', 'Barra da Tijuca'),
('2804', 'Bangu - Barra da Tijuca', 'Bangu', 'Barra da Tijuca'),
('731', 'Campo Grande - Marechal Hermes', 'Campo Grande', 'Marechal Hermes'),
('SN731', 'Campo Grande - Marechal Hermes', 'Campo Grande', 'Marechal Hermes'),
('745', 'Bangu - Cascadura', 'Bangu', 'Cascadura'),
('746', 'Jabour - Cascadura', 'Jabour', 'Cascadura'),
('756', 'Santa Cruz - Coelho Neto', 'Santa Cruz', 'Coelho Neto'),
('759', 'Cesarão - Coelho Neto', 'Cesarão', 'Coelho Neto'),
('SV777', 'Padre Miguel - Madureira', 'Padre Miguel', 'Madureira'),
('790', 'Campo Grande - Cascadura', 'Campo Grande', 'Cascadura'),
('794', 'Bangu - Cascadura', 'Bangu', 'Cascadura'),
('801', 'Bangu - Taquara', 'Bangu', 'Taquara'),
('SP801', 'Bangu - Terminal Sulacap', 'Bangu', 'Terminal Sulacap'),
('809', 'Sagrado Coração - Santa Cruz', 'Sagrado Coração', 'Santa Cruz'),
('812', 'Carobinha - Bangu', 'Carobinha', 'Bangu'),
('2338', 'Terminal Campo Grande - Castelo', 'Terminal Campo Grande', 'Castelo'),
('770', 'Campo Grande - Metrô Coelho Neto', 'Campo Grande', 'Metrô Coelho Neto'),
('771', 'Campo Grande - Metrô Coelho Neto', 'Campo Grande', 'Metrô Coelho Neto'),
('802', 'Terminal Campo Grande - Bangu', 'Terminal Campo Grande', 'Bangu'),
('SR397', 'Terminal Campo Grande - Candelária', 'Terminal Campo Grande', 'Candelária'),
('SN397', 'Terminal Campo Grande - Candelária', 'Terminal Campo Grande', 'Candelária'),
('SN790', 'Campo Grande - Cascadura', 'Campo Grande', 'Cascadura'),
('819', 'Jardim Bangu - Bangu', 'Jardim Bangu', 'Bangu'),
('821', 'Campo Grande - Corcundinha', 'Campo Grande', 'Corcundinha'),
('822', 'Campo Grande - Corcundinha', 'Campo Grande', 'Corcundinha'),
('825', 'Campo Grande - Jesuítas', 'Campo Grande', 'Jesuítas'),
('830', 'Pedregoso - Campo Grande', 'Pedregoso', 'Campo Grande'),
('833', 'Conjunto Manguariba - Campo Grande', 'Conjunto Manguariba', 'Campo Grande'),
('741', 'Terminal Sulacap - Bangu', 'Terminal Sulacap', 'Bangu'),
('743', 'Terminal Sulacap - Bangu', 'Terminal Sulacap', 'Bangu'),
('840', 'São Fernando - Campo Grande', 'São Fernando', 'Campo Grande'),
('842', 'Paciência - Campo Grande', 'Paciência', 'Campo Grande'),
('849', 'Base Aérea de Santa Cruz - Campo Grande', 'Base Aérea de Santa Cruz', 'Campo Grande'),
('851', 'Campo Grande - Escola Amazonas', 'Campo Grande', 'Escola Amazonas'),
('SV790', 'Campo Grande - Cascadura', 'Campo Grande', 'Cascadura'),
('SP918', 'Jardim Violeta - Terminal Deodoro', 'Jardim Violeta', 'Terminal Deodoro'),
('SN794', 'Jabour - Cascadura', 'Jabour', 'Cascadura'),
('869', 'Santa Margarida - Campo Grande', 'Santa Margarida', 'Campo Grande'),
('807', 'Jesuítas - Terminal Curral Falso', 'Jesuítas', 'Terminal Curral Falso'),
('SN803', 'Jabour - Taquara', 'Jabour', 'Taquara'),
('803', 'Jabour - Taquara', 'Jabour', 'Taquara'),
('870', 'Sepetiba - Santa Cruz', 'Sepetiba', 'Santa Cruz'),
('835', 'Largo do Correia - Terminal Campo Grande', 'Largo do Correia', 'Terminal Campo Grande'),
('837', 'Terminal Campo Grande - Conjunto da Marinha', 'Terminal Campo Grande', 'Conjunto da Marinha'),
('838', 'Terminal Campo Grande - Terminal Magarça', 'Terminal Campo Grande', 'Terminal Magarça'),
('846', 'Rio da Prata - Terminal Campo Grande', 'Rio da Prata', 'Terminal Campo Grande'),
('852', 'Terminal Campo Grande - Pedra de Guaratiba', 'Terminal Campo Grande', 'Pedra de Guaratiba'),
('866', 'Terminal Campo Grande - Pedra de Guaratiba', 'Terminal Campo Grande', 'Pedra de Guaratiba'),
('867', 'Barra de Guaratiba - Terminal Campo Grande', 'Barra de Guaratiba', 'Terminal Campo Grande'),
('884', 'Sepetiba - Terminal Campo Grande', 'Sepetiba', 'Terminal Campo Grande'),
('SN884', 'Sepetiba - Terminal Campo Grande', 'Sepetiba', 'Terminal Campo Grande'),
('SN840', 'São Fernando - Campo Grande', 'São Fernando', 'Campo Grande'),
('SN867', 'Barra de Guaratiba - Terminal Campo Grande', 'Barra de Guaratiba', 'Terminal Campo Grande'),
('892', 'São Benedito - Santa Cruz', 'São Benedito', 'Santa Cruz'),
('893', 'Jardim Palmares - Campo Grande', 'Jardim Palmares', 'Campo Grande'),
('895', 'Serrinha - Campo Grande', 'Serrinha', 'Campo Grande'),
('843', 'Boa Esperança - Campo Grande', 'Boa Esperança', 'Campo Grande'),
('898', 'Sepetiba - Campo Grande', 'Sepetiba', 'Campo Grande'),
('918', 'Bangu - Bonsucesso', 'Bangu', 'Bonsucesso'),
('926', 'Senador Camará - Penha', 'Senador Camará', 'Penha'),
('006', 'Silvestre - Castelo', 'Silvestre', 'Castelo'),
('107', 'Central - Urca', 'Central', 'Urca'),
('SN846', 'Rio da Prata - Terminal Campo Grande', 'Rio da Prata', 'Terminal Campo Grande'),
('SN821', 'Campo Grande - Corcundinha', 'Campo Grande', 'Corcundinha'),
('872', 'Praia de Sepetiba - Terminal Mato Alto', 'Praia de Sepetiba', 'Terminal Mato Alto'),
('883', 'Terminal Mato Alto - Terminal Deodoro', 'Terminal Mato Alto', 'Terminal Deodoro'),
('SN897', 'Santa Cruz - Terminal Pingo d''Água', 'Santa Cruz', 'Terminal Pingo d''Água'),
('201', 'Santa Alexandrina - Castelo', 'Santa Alexandrina', 'Castelo'),
('202', 'Rio Comprido - Castelo', 'Rio Comprido', 'Castelo'),
('210', 'Caju - Candelária', 'Caju', 'Candelária'),
('217', 'Andaraí - Carioca', 'Andaraí', 'Carioca'),
('220', 'Usina - Candelária', 'Usina', 'Candelária'),
('229', 'Usina - Castelo', 'Usina', 'Castelo'),
('275', 'Méier - Candelária', 'Méier', 'Candelária'),
('836', 'Rio da Prata - Terminal Campo Grande', 'Rio da Prata', 'Terminal Campo Grande'),
('010', 'Bairro de Fátima - Central do Brasil', 'Bairro de Fátima', 'Central do Brasil'),
('854', 'Terminal Campo Grande - Ilha de Guaratiba', 'Terminal Campo Grande', 'Ilha de Guaratiba'),
('834', 'Terminal Campo Grande - Cabuçu de Baixo', 'Terminal Campo Grande', 'Cabuçu de Baixo'),
('409', 'Saens Peña - Horto', 'Saens Peña', 'Horto'),
('410', 'Saens Peña - Gávea', 'Saens Peña', 'Gávea'),
('415', 'Usina - Leblon', 'Usina', 'Leblon'),
('SN415', 'Usina - Leblon', 'Usina', 'Leblon'),
('422', 'Grajaú - Cosme Velho', 'Grajaú', 'Cosme Velho'),
('841', 'Campo Grande - Inhoaíba', 'Campo Grande', 'Inhoaíba'),
('SN422', 'Grajaú - Cosme Velho', 'Grajaú', 'Cosme Velho'),
('SN898', 'Sepetiba - Campo Grande', 'Sepetiba', 'Campo Grande'),
('SN133', 'Largo do Machado - Terminal Gentileza', 'Largo do Machado', 'Terminal Gentileza'),
('SN893', 'Jardim Palmares - Campo Grande', 'Jardim Palmares', 'Campo Grande'),
('426', 'Usina - Jardim de Alah', 'Usina', 'Jardim de Alah'),
('100', 'General Osório - Central', 'General Osório', 'Central'),
('SP864', 'Terminal Campo Grande - Bangu', 'Terminal Campo Grande', 'Bangu'),
('007', 'Silvestre - Central do Brasil', 'Silvestre', 'Central do Brasil'),
('LECD135', 'Paula Matos - Central do Brasil', 'Paula Matos', 'Central do Brasil'),
('117', 'Central - Cosme Velho', 'Central', 'Cosme Velho'),
('435', 'Grajaú - Gávea', 'Grajaú', 'Gávea'),
('209', 'Candelária - Caju', 'Candelária', 'Caju'),
('461', 'São Cristóvão - Ipanema', 'São Cristóvão', 'Ipanema'),
('472', 'Triagem - Leme', 'Triagem', 'Leme'),
('473', 'São Januário - Lido', 'São Januário', 'Lido'),
('474', 'Jacaré - Copacabana', 'Jacaré', 'Copacabana'),
('SV474', 'Jacaré - Copacabana', 'Jacaré', 'Copacabana'),
('476', 'Méier - Leblon', 'Méier', 'Leblon'),
('507', 'Silvestre - Largo do Machado', 'Silvestre', 'Largo do Machado'),
('539', 'Rocinha - Leme', 'Rocinha', 'Leme'),
('583', 'Cosme Velho - Leblon', 'Cosme Velho', 'Leblon'),
('584', 'Cosme Velho - Leblon', 'Cosme Velho', 'Leblon'),
('603', 'Usina - Saens Peña', 'Usina', 'Saens Peña'),
('608', 'Grajaú - Saens Peña', 'Grajaú', 'Saens Peña'),
('626', 'Saens Peña - Muda', 'Saens Peña', 'Muda'),
('498', 'Circular da Penha - Largo do Machado', 'Circular da Penha', 'Largo do Machado'),
('448', 'Furnas - São Conrado', 'Furnas', 'São Conrado');

INSERT INTO linha (numero_linha, nome_linha, origem, destino) VALUES
('513', 'Urca - Botafogo', 'Urca', 'Botafogo'),
('SN474', 'Méier - Copacabana', 'Méier', 'Copacabana'),
('553', 'Recreio dos Bandeirantes - Rio Sul', 'Recreio dos Bandeirantes', 'Rio Sul'),
('104', 'São Conrado - Terminal Gentileza', 'São Conrado', 'Terminal Gentileza'),
('335', 'Cordovil - Tiradentes', 'Cordovil', 'Tiradentes'),
('485', 'Fundão - General Osório', 'Fundão', 'General Osório'),
('SN483', 'Penha - General Osório', 'Penha', 'General Osório'),
('SP766', 'Três Rios - Madureira', 'Três Rios', 'Madureira'),
('SV483', 'General Osório - Penha', 'General Osório', 'Penha'),
('SPA483', 'Fiocruz - General Osório', 'Fiocruz', 'General Osório'),
('SPB483', 'Parque União - General Osório', 'Parque União', 'General Osório'),
('SV922', 'Tubiacanga - Fundão', 'Tubiacanga', 'Fundão'),
('SV384', 'Pavuna - Passeio', 'Pavuna', 'Passeio'),
('SPA550', 'Cidade de Deus - Rocinha', 'Cidade de Deus', 'Rocinha'),
('SP759', 'Cesarão - Terminal Deodoro', 'Cesarão', 'Terminal Deodoro'),
('SP805', 'Terminal Alvorada - Passarela da Barra', 'Terminal Alvorada', 'Passarela da Barra'),
('987', 'Gardênia Azul - Pechincha', 'Gardênia Azul', 'Pechincha'),
('808', 'Salim - Campo Grande', 'Salim', 'Campo Grande'),
('899', 'Barra de Guaratiba - Terminal Recreio', 'Barra de Guaratiba', 'Terminal Recreio'),
('SN209', 'Candelária - Caju', 'Candelária', 'Caju'),
('990', 'Merck - Joatinga', 'Merck', 'Joatinga'),
('SV899', 'Barra de Guaratiba - Terminal Recreio', 'Barra de Guaratiba', 'Terminal Recreio'),
('645', 'Terminal Alvorada - Saens Peña', 'Terminal Alvorada', 'Saens Peña'),
('SVB901', 'Bonsucesso - Bananal', 'Bonsucesso', 'Bananal'),
('817', 'Piabas - Vargem Grande', 'Piabas', 'Vargem Grande'),
('300', 'Terminal Sulacap - Candelária', 'Terminal Sulacap', 'Candelária'),
('552', 'Terminal Alvorada - Rio Sul', 'Terminal Alvorada', 'Rio Sul'),
('554', 'Piabas - Rio Sul', 'Piabas', 'Rio Sul'),
('921', 'Bancários - Ribeira', 'Bancários', 'Ribeira'),
('881', 'Taquara - Terminal Alvorada', 'Taquara', 'Terminal Alvorada'),
('371', 'Praça Seca - Praça Tiradentes', 'Praça Seca', 'Praça Tiradentes'),
('SR399', 'Pavuna - Passeio', 'Pavuna', 'Passeio'),
('SR388', 'Santa Cruz - Candelária', 'Santa Cruz', 'Candelária'),
('757', 'Sepetiba - Coelho Neto', 'Sepetiba', 'Coelho Neto'),
('397', 'Terminal Campo Grande - Candelária', 'Terminal Campo Grande', 'Candelária'),
('847', 'Rio da Prata - Terminal Campo Grande', 'Rio da Prata', 'Terminal Campo Grande'),
('350', 'Irajá - Castelo', 'Irajá', 'Castelo'),
('SN328', 'Bananal - Candelária', 'Bananal', 'Candelária'),
('SN368', 'Riocentro - Candelária', 'Riocentro', 'Candelária'),
('SN880', 'Rio das Pedras - Terminal Alvorada', 'Rio das Pedras', 'Terminal Alvorada'),
('SN388', 'Santa Cruz - Candelária', 'Santa Cruz', 'Candelária'),
('SN355', 'Madureira - Praça Tiradentes', 'Madureira', 'Praça Tiradentes'),
('SN399', 'Pavuna - Passeio', 'Pavuna', 'Passeio'),
('783', 'Terminal Deodoro - Praça Seca', 'Terminal Deodoro', 'Praça Seca'),
('788', 'Terminal Campo Grande - Terminal Deodoro', 'Terminal Campo Grande', 'Terminal Deodoro'),
('796', 'Campo Grande - Terminal Deodoro', 'Campo Grande', 'Terminal Deodoro'),
('SR384', 'Pavuna - Passeio', 'Pavuna', 'Passeio'),
('SR386', 'Anchieta - Candelária', 'Anchieta', 'Candelária'),
('SN861', 'Rio das Pedras - Curicica', 'Rio das Pedras', 'Curicica'),
('SN497', 'Penha - Largo do Machado', 'Penha', 'Largo do Machado'),
('133', 'Largo do Machado - Terminal Gentileza', 'Largo do Machado', 'Terminal Gentileza'),
('301', 'Terminal Gentileza - Terminal Alvorada', 'Terminal Gentileza', 'Terminal Alvorada'),
('SR328', 'Bananal - Candelária', 'Bananal', 'Candelária'),
('SV391', 'Padre Miguel - Praça da República', 'Padre Miguel', 'Praça da República'),
('897', 'Paciência - Terminal Pingo d''Água', 'Paciência', 'Terminal Pingo d''Água'),
('871', 'Terminal Pingo d''Água - Cesarão', 'Terminal Pingo d''Água', 'Cesarão'),
('SN624', 'Mariópolis - Praça da República', 'Mariópolis', 'Praça da República'),
('785', 'Cascadura - Marechal Hermes', 'Cascadura', 'Marechal Hermes'),
('653', 'Terminal Deodoro - Méier', 'Terminal Deodoro', 'Méier'),
('764', 'Catiri - Terminal Deodoro', 'Catiri', 'Terminal Deodoro'),
('798', 'Campo Grande - Terminal Deodoro', 'Campo Grande', 'Terminal Deodoro'),
('606', 'Engenho de Dentro - Terminal Gentileza', 'Engenho de Dentro', 'Terminal Gentileza'),
('SN600', 'Taquara - Saens Peña', 'Taquara', 'Saens Peña'),
('SN104', 'São Conrado - Terminal Gentileza', 'São Conrado', 'Terminal Gentileza'),
('919', 'Pavuna - Bonsucesso', 'Pavuna', 'Bonsucesso'),
('SN919', 'Pavuna - Maré', 'Pavuna', 'Maré'),
('SN885', 'Terminal Mato Alto - Santa Cruz', 'Terminal Mato Alto', 'Santa Cruz'),
('SN825', 'Campo Grande - Jesuítas', 'Campo Grande', 'Jesuítas'),
('165', 'Terminal Gentileza - Cosme Velho', 'Terminal Gentileza', 'Cosme Velho'),
('161', 'Terminal Gentileza - Ipanema', 'Terminal Gentileza', 'Ipanema'),
('737', 'Santíssimo - Cascadura', 'Santíssimo', 'Cascadura'),
('826', 'Carobinha - Campo Grande', 'Carobinha', 'Campo Grande'),
('SN007', 'Silvestre - Central', 'Silvestre', 'Central'),
('SN895', 'Serrinha - Campo Grande', 'Serrinha', 'Campo Grande'),
('SN634', 'Bananal - Saens Peña', 'Bananal', 'Saens Peña'),
('857', 'Terminal Campo Grande - Terminal Pingo d''Água', 'Terminal Campo Grande', 'Terminal Pingo d''Água'),
('SN857', 'Terminal Campo Grande - Terminal Pingo D''Água', 'Terminal Campo Grande', 'Terminal Pingo D''Água'),
('SN353', 'Gardênia Azul - Terminal Gentileza', 'Gardênia Azul', 'Terminal Gentileza'),
('SN312', 'Penha - Candelária', 'Penha', 'Candelária'),
('SP795', 'Pavuna - Terminal Deodoro', 'Pavuna', 'Terminal Deodoro'),
('SV921', 'Bancários - Ribeira', 'Bancários', 'Ribeira'),
('353', 'Gardênia Azul - Terminal Gentileza', 'Gardênia Azul', 'Terminal Gentileza'),
('SP265', 'Marechal Hermes - Terminal Gentileza', 'Marechal Hermes', 'Terminal Gentileza'),
('167', 'Terminal Gentileza - Urca', 'Terminal Gentileza', 'Urca'),
('754', 'Santa Cruz - Terminal Deodoro', 'Santa Cruz', 'Terminal Deodoro'),
('855', 'Terminal Magarça - Terminal Deodoro', 'Terminal Magarça', 'Terminal Deodoro'),
('922', 'Tubiacanga - Terminal Fundão', 'Tubiacanga', 'Terminal Fundão'),
('779', 'Metrô Pavuna - Terminal Madureira', 'Metrô Pavuna', 'Terminal Madureira'),
('SN779', 'Metrô Pavuna - Terminal Madureira', 'Metrô Pavuna', 'Terminal Madureira'),
('SV863', 'Rio das Pedras - Barra da Tijuca', 'Rio das Pedras', 'Barra da Tijuca'),
('324', 'Ribeira - Candelária', 'Ribeira', 'Candelária'),
('SPB326', 'Bancários - Terminal Fundão', 'Bancários', 'Terminal Fundão'),
('SP324', 'Ribeira - Terminal Fundão', 'Ribeira', 'Terminal Fundão'),
('SP328', 'Bananal - Terminal Fundão', 'Bananal', 'Terminal Fundão'),
('SP329', 'Bancários - Terminal Fundão', 'Bancários', 'Terminal Fundão'),
('SV624', 'Mariópolis - Praça da Bandeira', 'Mariópolis', 'Praça da Bandeira'),
('651', 'Cascadura - Méier', 'Cascadura', 'Méier'),
('616', 'Del Castilho - Fundão', 'Del Castilho', 'Fundão'),
('786', 'Terminal Campo Grande - Cascadura', 'Terminal Campo Grande', 'Cascadura'),
('961', 'Rio das Pedras - Recreio dos Bandeirantes', 'Rio das Pedras', 'Recreio dos Bandeirantes'),
('894', 'Terminal Campo Grande - Jardim Moriçaba', 'Terminal Campo Grande', 'Jardim Moriçaba'),
('585', 'Largo do Machado - Jardim de Alah', 'Largo do Machado', 'Jardim de Alah'),
('908', 'Terminal Deodoro - Bonsucesso', 'Terminal Deodoro', 'Bonsucesso'),
('SN908', 'Terminal Deodoro - Bonsucesso', 'Terminal Deodoro', 'Bonsucesso'),
('853', 'Terminal Mato Alto - Terminal Deodoro', 'Terminal Mato Alto', 'Terminal Deodoro'),
('850', 'Mendanha - Campo Grande', 'Mendanha', 'Campo Grande'),
('SN696', 'Méier - Praia do Dendê', 'Méier', 'Praia do Dendê'),
('856', 'Capoeira Grande - Terminal Campo Grande', 'Capoeira Grande', 'Terminal Campo Grande'),
('SV908', 'Terminal Deodoro - Bonsucesso', 'Terminal Deodoro', 'Bonsucesso'),
('868', 'Urucânia - Campo Grande', 'Urucânia', 'Campo Grande'),
('SV853', 'Terminal Mato Alto - Terminal Deodoro', 'Terminal Mato Alto', 'Terminal Deodoro'),
('SN383', 'Realengo - Praça da República', 'Realengo', 'Praça da República'),
('SP389', 'Vila Aliança - Terminal Deodoro', 'Vila Aliança', 'Terminal Deodoro'),
('169', 'Terminal Gentileza - General Osório', 'Terminal Gentileza', 'General Osório'),
('780', 'Metrô Pavuna - Terminal Madureira', 'Metrô Pavuna', 'Terminal Madureira'),
('799', 'Metrô Pavuna - Bangu', 'Metrô Pavuna', 'Bangu'),
('SV917', 'Padre Miguel - Bonsucesso', 'Padre Miguel', 'Bonsucesso'),
('946', 'Pavuna - Engenho da Rainha', 'Pavuna', 'Engenho da Rainha'),
('975', 'Madureira - Terminal Fundão', 'Madureira', 'Terminal Fundão'),
('979', 'Terminal Madureira - Terminal Fundão', 'Terminal Madureira', 'Terminal Fundão'),
('820', 'Rio da Prata - Terminal Mato Alto', 'Rio da Prata', 'Terminal Mato Alto'),
('864', 'Terminal Campo Grande - Terminal Sulacap', 'Terminal Campo Grande', 'Terminal Sulacap'),
('SN848', 'Terminal Campo Grande - Monte Santo', 'Terminal Campo Grande', 'Monte Santo'),
('635', 'Bananal - Saens Peña', 'Bananal', 'Saens Peña'),
('SP635', 'Terminal Fundão - Saens Peña', 'Terminal Fundão', 'Saens Peña'),
('848', 'Terminal Campo Grande - Monte Santo', 'Terminal Campo Grande', 'Monte Santo'),
('LECD126', 'Méier - Parque Piedade', 'Méier', 'Parque Piedade'),
('2614', 'Terminal Alvorada - Metrô Del Castilho', 'Terminal Alvorada', 'Metrô Del Castilho'),
('2613', 'Riocentro - Metrô Del Castilho', 'Riocentro', 'Metrô Del Castilho'),
('SE298', 'Acari - Enseada de Botafogo', 'Acari', 'Enseada de Botafogo'),
('SE324', 'Ribeira - Enseada de Botafogo', 'Ribeira', 'Enseada de Botafogo'),
('SE328', 'Bananal - Enseada de Botafogo', 'Bananal', 'Enseada de Botafogo'),
('SE363', 'Vila Valqueire - Enseada de Botafogo', 'Vila Valqueire', 'Enseada de Botafogo'),
('SE368', 'Riocentro - Enseada de Botafogo', 'Riocentro', 'Enseada de Botafogo'),
('SE383', 'Realengo - Enseada de Botafogo', 'Realengo', 'Enseada de Botafogo'),
('SE388', 'Santa Cruz - Enseada de Botafogo', 'Santa Cruz', 'Enseada de Botafogo'),
('SE399', 'Pavuna - Enseada de Botafogo', 'Pavuna', 'Enseada de Botafogo'),
('SE553', 'Recreio dos Bandeirantes - Praia de Botafogo', 'Recreio dos Bandeirantes', 'Praia de Botafogo'),
('SE554', 'Piabas - Praia de Botafogo', 'Piabas', 'Praia de Botafogo'),
('925', 'Bancários - Aeroporto Internacional do RJ', 'Bancários', 'Aeroporto Internacional do RJ'),
('LECD128', 'Terminal Gentileza - Alto Gávea', 'Terminal Gentileza', 'Alto Gávea'),
('LECD129', 'Terminal Alvorada - Central do Brasil', 'Terminal Alvorada', 'Central do Brasil'),
('LECD130', 'Terminal Gentileza - Leblon', 'Terminal Gentileza', 'Leblon'),
('LECD131', 'São Conrado - Terminal Gentileza', 'São Conrado', 'Terminal Gentileza'),
('LECD132', 'Norte Shopping - Copacabana', 'Norte Shopping', 'Copacabana'),
('SN554', 'Piabas - Metrô Botafogo', 'Piabas', 'Metrô Botafogo'),
('804', 'Terminal Curral Falso - Campo Grande', 'Terminal Curral Falso', 'Campo Grande'),
('917', 'Padre Miguel - Bonsucesso', 'Padre Miguel', 'Bonsucesso'),
('845', 'Cantagalo - Terminal Campo Grande', 'Cantagalo', 'Terminal Campo Grande'),
('239', 'Água Santa - Passeio', 'Água Santa', 'Passeio');

INSERT INTO linha (numero_linha, nome_linha, origem, destino) VALUES
('791', 'Padre Miguel - Terminal Deodoro', 'Padre Miguel', 'Terminal Deodoro'),
('691', 'Méier - Terminal Alvorada', 'Méier', 'Terminal Alvorada'),
('LECD134', 'Central do Brasil - Leblon', 'Central do Brasil', 'Leblon'),
('LECD133', 'Metrô São Cristóvão - Leblon', 'Metrô São Cristóvão', 'Leblon'),
('416', 'Saens Peña - Horto', 'Saens Peña', 'Horto'),
('LECD127', 'Gávea - Rodoviária', 'Gávea', 'Rodoviária'),
('LECD137', 'Terminal Alvorada - Central do Brasil', 'Terminal Alvorada', 'Central do Brasil'),
('LECD136', 'Terminal Gentileza - Leme', 'Terminal Gentileza', 'Leme'),
('SN853', 'Terminal Mato Alto - Terminal Deodoro', 'Terminal Mato Alto', 'Terminal Deodoro'),
('SP485', 'Cidade Nova - Fundão', 'Cidade Nova', 'Fundão'),
('486', 'Fundão - General Osório', 'Fundão', 'General Osório'),
('LECD138', 'Rocinha - Leme', 'Rocinha', 'Leme'),
('LECD139', 'Saens Peña - Gávea', 'Saens Peña', 'Gávea'),
('LECD143', 'Metrô Pavuna - Terminal Margaridas', 'Metrô Pavuna', 'Terminal Margaridas'),
('LECD142', 'Madureira - Jardim América', 'Madureira', 'Jardim América'),
('LECD146', 'Metrô Vicente de Carvalho - Terminal Margaridas', 'Metrô Vicente de Carvalho', 'Terminal Margaridas'),
('LECD148', 'Terminal Margaridas - Méier', 'Terminal Margaridas', 'Méier'),
('SE100', 'Central - Enseada de Botafogo', 'Central', 'Enseada de Botafogo'),
('SE169', 'Terminal Gentileza - Enseada de Botafogo', 'Terminal Gentileza', 'Enseada de Botafogo'),
('SEB232', 'Lins de Vasconcelos - Enseada de Botafogo', 'Lins de Vasconcelos', 'Enseada de Botafogo'),
('SE238', 'Água Santa - Enseada de Botafogo', 'Água Santa', 'Enseada de Botafogo'),
('SE265', 'Marechal Hermes - Enseada de Botafogo', 'Marechal Hermes', 'Enseada de Botafogo'),
('SE312', 'Penha - Enseada de Botafogo', 'Penha', 'Enseada de Botafogo'),
('SE355', 'Madureira - Enseada de Botafogo', 'Madureira', 'Enseada de Botafogo'),
('SE393', 'Bangu - Enseada de Botafogo', 'Bangu', 'Enseada de Botafogo'),
('SE397', 'Terminal Campo Grande - Enseada de Botafogo', 'Terminal Campo Grande', 'Enseada de Botafogo'),
('SE410', 'Saens Peña - Enseada de Botafogo', 'Saens Peña', 'Enseada de Botafogo'),
('SE457', 'Abolição - Enseada de Botafogo', 'Abolição', 'Enseada de Botafogo'),
('SE474', 'Méier - Enseada de Botafogo', 'Méier', 'Enseada de Botafogo'),
('SE483', 'Penha - Enseada de Botafogo', 'Penha', 'Enseada de Botafogo'),
('SE550', 'Cidade de Deus - Praia de Botafogo', 'Cidade de Deus', 'Praia de Botafogo'),
('SE2338', 'Terminal Campo Grande - Praia de Botafogo', 'Terminal Campo Grande', 'Praia de Botafogo'),
('10', 'Santa Cruz - Terminal Alvorada', 'Santa Cruz', 'Terminal Alvorada'),
('11', 'Santa Cruz - Terminal Alvorada', 'Santa Cruz', 'Terminal Alvorada'),
('17', 'Campo Grande - Santa Cruz', 'Campo Grande', 'Santa Cruz'),
('18', 'Pontal - Terminal Jardim Oceânico', 'Pontal', 'Terminal Jardim Oceânico'),
('14', 'Santa Eugênia - Terminal Recreio', 'Santa Eugênia', 'Terminal Recreio'),
('80', 'Penha - Terminal Gentileza', 'Penha', 'Terminal Gentileza'),
('35', 'Terminal Madureira - Terminal Alvorada', 'Terminal Madureira', 'Terminal Alvorada'),
('41', 'Terminal Madureira - Terminal Recreio', 'Terminal Madureira', 'Terminal Recreio'),
('42', 'Galeão - Madureira', 'Galeão', 'Madureira'),
('52', 'Terminal Deodoro - Terminal Alvorada', 'Terminal Deodoro', 'Terminal Alvorada'),
('53', 'Terminal Sulacap - Terminal Alvorada', 'Terminal Sulacap', 'Terminal Alvorada'),
('ESP01', 'Galeão - Terminal Gentileza', 'Galeão', 'Terminal Gentileza'),
('20', 'Santa Cruz - Salvador Allende', 'Santa Cruz', 'Salvador Allende'),
('46', 'Penha - Terminal Alvorada', 'Penha', 'Terminal Alvorada'),
('15', 'Terminal Curral Falso - Terminal Alvorada', 'Terminal Curral Falso', 'Terminal Alvorada'),
('13', 'Terminal Mato Alto - Terminal Alvorada', 'Terminal Mato Alto', 'Terminal Alvorada'),
('25', 'Terminal Mato Alto - Terminal Alvorada', 'Terminal Mato Alto', 'Terminal Alvorada'),
('12', 'Terminal Pingo d''Água - Terminal Alvorada', 'Terminal Pingo d''Água', 'Terminal Alvorada'),
('90', 'Terminal Fundão - Terminal Gentileza', 'Terminal Fundão', 'Terminal Gentileza'),
('19', 'Terminal Pingo d''Água - Salvador Allende', 'Terminal Pingo d''Água', 'Salvador Allende'),
('16', 'Magarça - Terminal Alvorada', 'Magarça', 'Terminal Alvorada'),
('60', 'Terminal Deodoro - Terminal Gentileza', 'Terminal Deodoro', 'Terminal Gentileza'),
('61', 'Terminal Deodoro - Terminal Gentileza', 'Terminal Deodoro', 'Terminal Gentileza'),
('22', 'Terminal Alvorada - Terminal Jardim Oceânico', 'Terminal Alvorada', 'Terminal Jardim Oceânico'),
('70', 'Terminal Margaridas - Terminal Gentileza', 'Terminal Margaridas', 'Terminal Gentileza'),
('68', 'Bangu - Terminal Deodoro', 'Bangu', 'Terminal Deodoro'),
('73', 'Terminal Margaridas - Terminal Gentileza', 'Terminal Margaridas', 'Terminal Gentileza'),
('51', 'Terminal Deodoro - Terminal Recreio', 'Terminal Deodoro', 'Terminal Recreio'),
('28', 'Terminal Pingo d''Água - Terminal Curral Falso', 'Terminal Pingo d''Água', 'Terminal Curral Falso'),
('67', 'Terminal Campo Grande - Terminal Deodoro', 'Terminal Campo Grande', 'Terminal Deodoro'),
('50', 'Terminal Jardim Oceânico - Terminal Centro Olímpico', 'Terminal Jardim Oceânico', 'Terminal Centro Olímpico'),
('43', 'Terminal Fundão - Santa Efigênia', 'Terminal Fundão', 'Santa Efigênia'),
('31', 'Vicente de Carvalho - Terminal Alvorada', 'Vicente de Carvalho', 'Terminal Alvorada'),
('40', 'Terminal Madureira - Terminal Alvorada', 'Terminal Madureira', 'Terminal Alvorada');
